// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.0
// source: proto/knight/knight.proto

package protoknight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddKnightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AddKnightReq) Reset() {
	*x = AddKnightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddKnightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKnightReq) ProtoMessage() {}

func (x *AddKnightReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKnightReq.ProtoReflect.Descriptor instead.
func (*AddKnightReq) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{0}
}

func (x *AddKnightReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddKnightReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddKnightReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AddKnightRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsActive bool   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *AddKnightRes) Reset() {
	*x = AddKnightRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddKnightRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKnightRes) ProtoMessage() {}

func (x *AddKnightRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKnightRes.ProtoReflect.Descriptor instead.
func (*AddKnightRes) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{1}
}

func (x *AddKnightRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddKnightRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddKnightRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddKnightRes) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type KnightStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *KnightStatusReq) Reset() {
	*x = KnightStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnightStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnightStatusReq) ProtoMessage() {}

func (x *KnightStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnightStatusReq.ProtoReflect.Descriptor instead.
func (*KnightStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{2}
}

func (x *KnightStatusReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type KnightStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsActive bool `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *KnightStatusRes) Reset() {
	*x = KnightStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnightStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnightStatusRes) ProtoMessage() {}

func (x *KnightStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnightStatusRes.ProtoReflect.Descriptor instead.
func (*KnightStatusRes) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{3}
}

func (x *KnightStatusRes) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateStatusRes) Reset() {
	*x = UpdateStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knight_knight_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRes) ProtoMessage() {}

func (x *UpdateStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knight_knight_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRes.ProtoReflect.Descriptor instead.
func (*UpdateStatusRes) Descriptor() ([]byte, []int) {
	return file_proto_knight_knight_proto_rawDescGZIP(), []int{5}
}

var File_proto_knight_knight_proto protoreflect.FileDescriptor

var file_proto_knight_knight_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2f, 0x6b,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x22, 0x5c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4b,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6d, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4b, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22,
	0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x32, 0xed, 0x01, 0x0a, 0x0d, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4b, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6b, 0x6e, 0x69, 0x67,
	0x68, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x61, 0x66, 0x65, 0x74, 0x7a, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x65,
	0x6d, 0x6f, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6b,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_knight_knight_proto_rawDescOnce sync.Once
	file_proto_knight_knight_proto_rawDescData = file_proto_knight_knight_proto_rawDesc
)

func file_proto_knight_knight_proto_rawDescGZIP() []byte {
	file_proto_knight_knight_proto_rawDescOnce.Do(func() {
		file_proto_knight_knight_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_knight_knight_proto_rawDescData)
	})
	return file_proto_knight_knight_proto_rawDescData
}

var file_proto_knight_knight_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_knight_knight_proto_goTypes = []interface{}{
	(*AddKnightReq)(nil),    // 0: protoknight.AddKnightReq
	(*AddKnightRes)(nil),    // 1: protoknight.AddKnightRes
	(*KnightStatusReq)(nil), // 2: protoknight.KnightStatusReq
	(*KnightStatusRes)(nil), // 3: protoknight.KnightStatusRes
	(*UpdateStatusReq)(nil), // 4: protoknight.UpdateStatusReq
	(*UpdateStatusRes)(nil), // 5: protoknight.UpdateStatusRes
}
var file_proto_knight_knight_proto_depIdxs = []int32{
	0, // 0: protoknight.KnightService.AddKnight:input_type -> protoknight.AddKnightReq
	2, // 1: protoknight.KnightService.GetKnightStatus:input_type -> protoknight.KnightStatusReq
	4, // 2: protoknight.KnightService.UpdateStatus:input_type -> protoknight.UpdateStatusReq
	1, // 3: protoknight.KnightService.AddKnight:output_type -> protoknight.AddKnightRes
	3, // 4: protoknight.KnightService.GetKnightStatus:output_type -> protoknight.KnightStatusRes
	5, // 5: protoknight.KnightService.UpdateStatus:output_type -> protoknight.UpdateStatusRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_knight_knight_proto_init() }
func file_proto_knight_knight_proto_init() {
	if File_proto_knight_knight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_knight_knight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddKnightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knight_knight_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddKnightRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knight_knight_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnightStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knight_knight_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnightStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knight_knight_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knight_knight_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_knight_knight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_knight_knight_proto_goTypes,
		DependencyIndexes: file_proto_knight_knight_proto_depIdxs,
		MessageInfos:      file_proto_knight_knight_proto_msgTypes,
	}.Build()
	File_proto_knight_knight_proto = out.File
	file_proto_knight_knight_proto_rawDesc = nil
	file_proto_knight_knight_proto_goTypes = nil
	file_proto_knight_knight_proto_depIdxs = nil
}
